### PR TITLE
Change lexer to match the grammar specified in RFC4288

### LINKED ISSUE #2: Parsing does not conform to the ABNF in RFC4288
RFC4288 section 4.2 says this is the ABNF for mime types:

```
   Type and subtype names MUST conform to the following ABNF:

       type-name = reg-name
       subtype-name = reg-name

       reg-name = 1*127reg-name-chars
       reg-name-chars = ALPHA / DIGIT / "!" /
                       "#" / "$" / "&" / "." /
                       "+" / "-" / "^" / "_"
```

This should allow multiple + characters, but currently mimetype_parser does not allow this.

For example: `application/vnd.foo+hal+json` should be allowed.

### PR DESCRIPTION
**Pull request by pezra**
fixes #2

### CODE REVIEW

**Comment by alakra** [comment]
:+1:

**Comment by pezra** [comment]
@camshaft, any feed back?

**Comment by alakra** [comment]
Bump.

**Comment by camshaft** [comment]
yeah looks good. thanks.

**Pull request merged**
